language: node_js
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
notifications:
  email: false
cache:
  directories:
    - node_modules
# allow headful tests
before_install:
  - "npm i -g npm@6.1.0"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - 'if [ "$NODE7" = "true" ]; then npm run lint; fi'
  - 'if [ "$NODE7" = "true" ]; then npm run coverage; fi'
  - 'if [ "$NODE7" = "true" ]; then npm run test-doclint; fi'
  - 'if [ "$NODE6" = "true" ]; then npm run unit-node6; fi'
jobs:
  include:
    - node_js: "7.10.1"
      env: NODE7=true
    - node_js: "6.12.3"
      env: NODE6=true
before_deploy: "npm run apply-next-version"
deploy:
  provider: npm
  email: aslushnikov@gmail.com
  api_key:
    secure: I/evsRDAs9cNyTrPFbI3RJiMfr57PddSSq+ee5o3zpE6EOBdhPFk11jrEVxCArNZ7kwVujxps1O2gJEYTBO83AFaeMVRHFBHL8lLK8heOAlZeNc85mcLaPie6j0odtX/kKXD/o8YiX5XBEz8TBeO/z5L/23bz0tFn1Din78um3doJGTsgGX33kTzyOnz6xotGjUC2sO48dCJ1dT5B4BDRzTVNESCtqJ+klxnvrpGvsIacTcObHy7XrGc/Z/HwYgdphnRWcrxx8DPNtTv5wg8Avn8DBACvAEUnfkhj/neKcTPJDy5/BMU+eEXtba+CxYzLLQ6g9504rk7Ofxc2KM1byHdlkBAQ9vyShEie8t+x5GQwo2ykz+VoLDO2cG0WZ1MUxuXvxRoXz1kfXBjlxd/1m1toWykLK40FLyq+w+dcRRBT9c/y8xerXGw0Avmu2pHfyauDfMFmjFLw2jGNXPhRL/WaZvBnLroZWUmPNbUdOj4aJNglx8MNb81siQfUxvydnjUHmb9tRoMINRXuEShnuTPlQEfmVVcqJBnIgjpY1ZZ/dyB9yxQn12GLdZ3YGMbyvF9sxBDBXNsT+rwHJtGGYs0mKnKsWNDXORxOLSNDfKoq3WKHrrczoCDGglOLcbK3p2ghoeNOgf1nw9gaTiBHQvjtmwOtaxTCnLboiXqnHo=
  on:
    branch: master
    condition: "$NODE7 = true"
  skip_cleanup: true
  tag: next
