language: node_js
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
  # puppeteer's install script downloads Chrome
script:
  - 'if [ "$NODE7" = "true" ]; then yarn run lint; fi'
  - 'if [ "$NODE7" = "true" ]; then yarn run coverage; fi'
  - 'if [ "$NODE7" = "true" ]; then yarn run test-doclint; fi'
  - 'if [ "$NODE6" = "true" ]; then yarn run test-node6-transformer; fi'
  - 'if [ "$NODE6" = "true" ]; then yarn run build; fi'
  - 'if [ "$NODE6" = "true" ]; then yarn run unit-node6; fi'
jobs:
  include:
    - node_js: "7"
      env: NODE7=true
    - node_js: "6.4.0"
      env: NODE6=true
