name: Puppeteer Canary CI

# Declare default permissions as read only.
permissions: read-all

on:
  schedule:
    # Run everyday at: https://crontab.guru/#0_8_*_*_1-5.
    - cron: '0 8 * * 1-5'
  workflow_dispatch:

jobs:
  chrome-canary-tests:
    name: ${{ matrix.suite }} tests on ${{ matrix.os }} (${{ matrix.shard }}) ${{ matrix.configs }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        suite:
          - chrome-headless
          # - chrome-headful
          # - chrome-headless-shell
          - chrome-bidi
        os:
          - ubuntu-latest
          # - windows-latest
          # - macos-15
        shard:
          - 1-1
          # - 1-2
          # - 2-2
        configs:
          - stable
        # exclude:
        #   - os: windows-latest
        #     suite: chrome-bidi
        #   - os: macos-15
        #     suite: chrome-headful
    steps:
      - name: Check out repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Set up Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          cache: npm
          node-version-file: '.nvmrc'
      - name: Disable AppArmor
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
      - name: Install dependencies
        run: npm ci
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
      # Set up GitHub Actions caching for Wireit.
      - uses: google/wireit@f21db1f3a6a4db31f42787a958cf2a18308effed # setup-github-actions-caching/v2.0.3
      - name: Build packages
        run: npm run build -w @puppeteer-test/test
      - name: Install browsers
        run: npm run postinstall
        env:
          PUPPETEER_CHROME_VERSION: canary
          PUPPETEER_CHROME_HEADLESS_SHELL_VERSION: canary
          PUPPETEER_FIREFOX_SKIP_DOWNLOAD: true
      - name: Apply Canary expectations
        run: node tools/merge-canary-test-expectations.mjs
      - name: Run all tests (MacOS)
        if: ${{ matrix.os == 'macos-15' }}
        run: npm run test -- --ignore-unexpectedly-passing --test-suite ${{ matrix.suite }} --save-stats-to /tmp/artifacts/${{ github.event_name }}_INSERTID.json
        env:
          PUPPETEER_CHROME_VERSION: canary
          PUPPETEER_CHROME_HEADLESS_SHELL_VERSION: canary
          PUPPETEER_CHROME_HEADLESS_SHELL_SKIP_DOWNLOAD: true
          PUPPETEER_TEST_EXPERIMENTAL_CHROME_FEATURES: ${{ matrix.configs == 'experimental' }}
          DEBUG: "*"
      - name: Run all tests (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: npm run test -- --ignore-unexpectedly-passing --test-suite ${{ matrix.suite }} --save-stats-to /tmp/artifacts/${{ github.event_name }}_INSERTID.json
        env:
          PUPPETEER_CHROME_VERSION: canary
          PUPPETEER_CHROME_HEADLESS_SHELL_VERSION: canary
          PUPPETEER_CHROME_HEADLESS_SHELL_SKIP_DOWNLOAD: true
          PUPPETEER_TEST_EXPERIMENTAL_CHROME_FEATURES: ${{ matrix.configs == 'experimental' }}
          DEBUG: "*"
      - name: Run all tests (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: xvfb-run --auto-servernum npm run test -- --ignore-unexpectedly-passing --test-suite ${{ matrix.suite }} --save-stats-to /tmp/artifacts/${{ github.event_name }}_INSERTID.json
        env:
          PUPPETEER_CHROME_VERSION: canary
          PUPPETEER_CHROME_HEADLESS_SHELL_VERSION: canary
          PUPPETEER_CHROME_HEADLESS_SHELL_SKIP_DOWNLOAD: true
          PUPPETEER_TEST_EXPERIMENTAL_CHROME_FEATURES: ${{ matrix.configs == 'experimental' }}
          DEBUG: "*"
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        if: ${{ !cancelled() }}
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.suite }}-${{ matrix.shard }}-${{ matrix.configs }}
          path: /tmp/artifacts/*.json
