name: DevTools CI

# Declare default permissions as read only.
permissions: read-all

on:
  pull_request:
    types: [labeled]

concurrency:
  group: devtools-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-puppeteer:
    name: Build Puppeteer
    runs-on: ubuntu-latest
    if: contains(github.event.label.name, 'devtools')
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          cache: npm
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
      - name: Build Puppeteer
        run: |
          npm run build -w @puppeteer/browsers
          npm run build -w puppeteer-core
          npm run build -w puppeteer
      - name: Pack Puppeteer
        run: |
          npm pack -w @puppeteer/browsers
          npm pack -w puppeteer-core
          npm pack -w puppeteer
      - name: Upload Puppeteer build
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: puppeteer-build
          if-no-files-found: error
          path: puppeteer-*.tgz

  devtools-tests:
    name: DevTools tests
    needs: build-puppeteer
    runs-on: ubuntu-latest
    steps:
      - name: Download Puppeteer build
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: puppeteer-build
      - name: Disable AppArmor
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
      - name: Checkout depot_tools
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      - name: Add depot_tools to path
        run: echo $(realpath depot_tools) >> $GITHUB_PATH
      - name: Fetch devtools-frontend
        run: fetch devtools-frontend
      - name: Sync gclient
        working-directory: devtools-frontend
        run: gclient sync
      - name: Install Puppeteer
        working-directory: devtools-frontend
        run: |
          npm install ../puppeteer-browsers*.tgz ../puppeteer-core*.tgz
      - name: Generate targets
        working-directory: devtools-frontend
        run: gn gen out/Default --args='devtools_skip_typecheck=true'
      - name: Run tests
        working-directory: devtools-frontend
        run: npm run auto-e2etest
