# This workflow will update the pinned browsers

name: 'Update the pinned browsers'

permissions: read-all

on:
  schedule:
    # Run everyday at: https://crontab.guru/#0_6_*_*_*.
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: google/wireit@f3a3c79c553122e2fe5829eeac7d815326502903 # setup-github-actions-caching/v1
      - name: Install npm dependencies
        run: npm ci
      - name: Build Puppeteer
        run: npm run build -w puppeteer
      - name: Update Chrome to latest stable version
        id: update
        run: |
          node tools/update_chrome_revision.mjs
      - name: Create Pull Request
        if: ${{ steps.update.outputs.commit }}
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          token: ${{ secrets.BROWSER_AUTOMATION_BOT_TOKEN }}
          branch: browser-automation-bot/update-browser-version-chrome
          delete-branch: true
          committer: Browser Automation Bot <browser-automation-bot@google.com>
          author: Browser Automation Bot <browser-automation-bot@google.com>
          commit-message: ${{ steps.update.outputs.commit }}
          title: ${{ steps.update.outputs.commit }}
          body: 'Automatically generated by https://github.com/puppeteer/puppeteer/blob/main/.github/workflows/update-browser-pins.yml'
          labels: dependencies
  update-firefox:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: google/wireit@f3a3c79c553122e2fe5829eeac7d815326502903 # setup-github-actions-caching/v1
      - name: Install npm dependencies
        run: npm ci
      - name: Build Puppeteer
        run: npm run build:test -w @puppeteer/browsers
      - name: Update Firefox to latest nightly version
        id: update
        run: |
          node packages/browsers/tools/updateVersions.mjs
      - name: Create Pull Request
        if: ${{ steps.update.outputs.commit }}
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          token: ${{ secrets.BROWSER_AUTOMATION_BOT_TOKEN }}
          branch: browser-automation-bot/update-browser-version-firefox
          delete-branch: true
          committer: Browser Automation Bot <browser-automation-bot@google.com>
          author: Browser Automation Bot <browser-automation-bot@google.com>
          commit-message: ${{ steps.update.outputs.commit }}
          title: ${{ steps.update.outputs.commit }}
          body: 'Automatically generated by https://github.com/puppeteer/puppeteer/blob/main/.github/workflows/update-browser-pins.yml'
          labels: dependencies
