# This workflow will update the pinned browsers

name: 'Update the pinned browsers'

permissions: read-all

on:
  schedule:
    # Run everyday at: https://crontab.guru/#0_6_*_*_*.
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Set up Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          cache: npm
          node-version: lts/*
      - uses: google/wireit@f3a3c79c553122e2fe5829eeac7d815326502903 # setup-github-actions-caching/v1
      - name: Install npm dependencies
        run: npm ci
      - name: Build Puppeteer
        run: npm run build -w puppeteer
      - name: Update Chrome to latest stable version
        id: update
        run: |
          node --experimental-fetch tools/update_chrome_revision.mjs
      - name: Format files if needed
        run: npm run format
      - name: Update package-lock.json
        run: npm install --ignore-scripts
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@284f54f989303d2699d373481a0cfa13ad5a6666 # v5.0.1
        with:
          token: ${{ secrets.BROWSER_AUTOMATION_BOT_TOKEN }}
          branch: browser-automation-bot/update-browser-version
          delete-branch: true
          committer: Browser Automation Bot <browser-automation-bot@google.com>
          author: Browser Automation Bot <browser-automation-bot@google.com>
          commit-message: 'feat(chrome): roll to Chrome ${{ steps.update.outputs.version }} (r${{ steps.update.outputs.revision }})'
          title: 'feat(chrome): roll to Chrome ${{ steps.update.outputs.version }} (r${{ steps.update.outputs.revision }} )'
          body: 'Automatically generated by https://github.com/puppeteer/puppeteer/blob/main/.github/workflows/update-browser-pins.yml'
          labels: dependencies
